apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: akuity-poc-apps
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchExpressions:
                - {key: akuity.io/argo-cd-cluster-name, operator: NotIn, values: [in-cluster]}
          - list:
              elements:
              - env: dev
              - env: staging
              - env: prod
  template:
    metadata:
      name: 'akuity-poc-app-{{env}}'
      annotations:
        kargo.akuity.io/authorized-stage: kargo-simple:{{env}}
    spec:
      project: default
      source:
        repoURL: git@github.com:jane-delivery/akuity-poc-app.git
        targetRevision: main
        path: 'app/env/{{env}}'
      destination:
        name: '{{name}}'
        namespace: 'akuity-poc-app-{{env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
