name: build

on:
  workflow_dispatch:
    inputs:
      bump-version:
        description: 'Bump version'
        required: true
        default: 'patch'

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=sha,format=long,prefix=
            type=raw,value=${{ github.ref_name }}-${{ github.sha }}
            type=semver,pattern={{raw}},value=v${{ inputs.bump-version }}
            type=semver,pattern={{raw}},value=${{ inputs.bump-version }}
          flavor:
            latest=false

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: |
            ${{ steps.meta.outputs.labels }}
            app.jane.commit.user=${{ github.actor }}
            app.jane.commit.branch=${{ github.head_ref || github.ref_name }}
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:${{ inputs.bump-version }}
          cache-to: type=inline
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:latest
          secrets: |
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
